version: '3.7'
services: 
    db: 
        image: mongo:4.0.3
    backend: 
        image: node:12.16.1
        volumes:
            - ./backend:/backend    
        ports:
            - 3000:3000
        command: bash -c "cd /backend && npm i && node app"
    frontend:
        image: nginx:1.16
        volumes:
            - ./frontend:/usr/share/nginx/html/
        ports:
            - 80:80          
